// SPDX-FileCopyrightText: 2025 Liamofthesky <157073227+Liamofthesky@users.noreply.github.com>
// SPDX-FileCopyrightText: 2025 ReconPangolin <67752926+ReconPangolin@users.noreply.github.com>
// SPDX-FileCopyrightText: 2025 taydeo <td12233a@gmail.com>
//
// SPDX-License-Identifier: AGPL-3.0-or-later AND MIT

using System.Linq;
using System.Text;
using Content.Trauma.Shared.Botany.Components;
using Content.Trauma.Shared.Botany.PlantAnalyzer;
using Robust.Client.AutoGenerated;
using Content.Client.UserInterface.Controls;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Trauma.Client.Botany.PlantAnalyzer.UI;

[GenerateTypedNameReferences]
public sealed partial class PlantAnalyzerWindow : FancyWindow
{
    [Dependency] private readonly IEntityManager _entityManager = default!;
    private readonly ButtonGroup _buttonGroupTop = new();

    private const string IndentedNewline = "\n   ";
    public PlantAnalyzerModes _internalmode = PlantAnalyzerModes.Scan;
    private int _internalGeneNumber = 0;
    private int _internalDatabaseNumber = 0;
    private List<GeneData> _internalGeneDatabank = new();
    private List<GasData> _internalConsumeGasesDatabank = new();
    private List<GasData> _internalExudeGasesDatabank = new();
    private List<ChemData> _internalChemicalsDatabank = new();

    public PlantAnalyzerWindow(PlantAnalyzerBoundUserInterface owner)
    {
        IoCManager.InjectDependencies(this);
        RobustXamlLoader.Load(this);

        Tabs.OnTabChanged += _ =>
        {
            if (Tabs.CurrentTab == 0)
                owner.AdvPressed(PlantAnalyzerModes.Scan);
            else if (Tabs.CurrentTab == 1)
                owner.AdvPressed(PlantAnalyzerModes.DeleteMutations);
            else if (Tabs.CurrentTab == 2)
                owner.AdvPressed(PlantAnalyzerModes.Extract);
            else if (Tabs.CurrentTab == 3)
                owner.AdvPressed(PlantAnalyzerModes.Implant);
        };

        StepDownExtract.OnPressed += _ => owner.GeneIterate(false, false);
        StepUpExtract.OnPressed += _ => owner.GeneIterate(true, false);
        StepDownDatabase.OnPressed += _ => owner.GeneIterate(false, true);
        StepUpDatabase.OnPressed += _ => owner.GeneIterate(true, true);

        DeleteDatabaseEntryButton.OnPressed += _ => owner.DeleteDatabaseEntry();
    }

    public void Populate(PlantAnalyzerCurrentMode msg)
    {
        _internalmode = msg.CurrentMode;
    }
    public void Populate(PlantAnalyzerCurrentCount msg)
    {
        _internalGeneNumber = msg.GeneIndex;
        _internalDatabaseNumber = msg.DatabaseIndex;
    }

    public void Populate(PlantAnalyzerSeedDatabank msg)
    {
        _internalGeneDatabank = msg.SeedData;
        _internalConsumeGasesDatabank = msg.ConsumeGasData;
        _internalExudeGasesDatabank = msg.ExudeGasData;
        _internalChemicalsDatabank = msg.ChemicalData;
    }

    public void PopulateUpdateButtons()
    {
        switch (_internalmode)
        {
            case PlantAnalyzerModes.Scan:
                Tabs.CurrentTab = 0;
                break;
            case PlantAnalyzerModes.DeleteMutations:
                Tabs.CurrentTab = 1;
                break;
            case PlantAnalyzerModes.Extract:
                Tabs.CurrentTab = 2;
                if (_internalGeneNumber < 0)
                {
                    GeneIndexExtract.Text = Loc.GetString($"plant-analyzer-invalid-gene");
                    return;
                }
                GeneIndexExtract.Text = SeedDataTypes.IdToString[_internalGeneNumber];
                break;
            case PlantAnalyzerModes.Implant:
                Tabs.CurrentTab = 3;
                if (_internalGeneDatabank.Count + _internalConsumeGasesDatabank.Count + _internalExudeGasesDatabank.Count + _internalChemicalsDatabank.Count <= 0)
                {
                    GeneIndexDatabase.Text = Loc.GetString($"plant-analyzer-invalid-database");
                }
                else
                {
                    GeneIndexDatabase.Text = "Selected ID: " + (_internalDatabaseNumber + 1).ToString();
                }
                GeneDatabaseListContainer.RemoveAllChildren();
                GeneDatabaseListContainer.AddChild(new Label
                {
                    Text = Loc.GetString("plant-analyzer-database-entries-header"),
                    Margin = new Thickness(10, 0, 0, 0),
                });
                int index = 1;
                foreach (GeneData gene in _internalGeneDatabank)
                {
                    int mutationID = gene.GeneID;
                    SeedDataTypes.SeedDataType mutationType = SeedDataTypes.IdToType[mutationID];
                    string mutationValue = mutationType switch
                    {
                        SeedDataTypes.SeedDataType.Float => $"{gene.GeneValue:F2}",
                        SeedDataTypes.SeedDataType.Int => $"{(int) gene.GeneValue:D0}",
                        SeedDataTypes.SeedDataType.HarvestType => Loc.GetString($"plant-analyzer-harvest-{(SeedDataTypes.SeedDataType) (int) gene.GeneValue}"),
                        SeedDataTypes.SeedDataType.Bool => gene.GeneValue >= 0.5f ? Loc.GetString("plant-analyzer-boolean-true") : Loc.GetString("plant-analyzer-boolean-false"),
                        _ => "N/A"
                    };
                    GeneDatabaseListContainer.AddChild(new RichTextLabel
                    {
                        Text = $"ID: {index} {SeedDataTypes.IdToString[mutationID]}: {mutationValue}",
                        Margin = new Thickness(0, 4),
                    });
                    index++;
                }
                foreach (GasData gene in _internalConsumeGasesDatabank)
                {
                    GeneDatabaseListContainer.AddChild(new RichTextLabel
                    {
                        Text = $"ID: {index} Consume {Loc.GetString($"gases-{gene.GasID.ToString()}")}: {gene.GasValue}",
                        Margin = new Thickness(0, 4),
                    });
                    index++;
                }
                foreach (GasData gene in _internalExudeGasesDatabank)
                {
                    GeneDatabaseListContainer.AddChild(new RichTextLabel
                    {
                        Text = $"ID: {index} Exude {Loc.GetString($"gases-{gene.GasID.ToString()}")}: {gene.GasValue}",
                        Margin = new Thickness(0, 4),
                    });
                    index++;
                }
                foreach (ChemData gene in _internalChemicalsDatabank)
                {
                    GeneDatabaseListContainer.AddChild(new RichTextLabel
                    {
                        Text = $"ID: {index} {gene.ChemID}: Min - {gene.ChemValue.Min}, Max - {gene.ChemValue.Max}, Potency Divisor - {gene.ChemValue.PotencyDivisor }, Inherent - {gene.ChemValue.Inherent}",
                        Margin = new Thickness(0, 4),
                    });
                    index++;
                }
                break;
        }
    }
    public void Populate(PlantAnalyzerScannedSeedPlantInformation msg)
    {
        var target = _entityManager.GetEntity(msg.TargetEntity);
        Title = Loc.GetString("plant-analyzer-interface-title");

        if (target == null)
        {
            NoData.Visible = true;
            return;
        }
        NoData.Visible = false;

        // Process message fields into strings.
        StringBuilder chemString = new();
        if (msg.SeedChem != null)
        {
            foreach (var chem in msg.SeedChem)
            {
                chemString.Append(IndentedNewline);
                chemString.Append(chem);
            }
        }

        //Funkystation - Fixed to include new gases
        StringBuilder exudeGases = new();
        if (msg.ExudeGases != null)
        {
            foreach (var gas in msg.ExudeGases)
            {
                exudeGases.Append(IndentedNewline);
                exudeGases.Append(gas);
            }
        }

        StringBuilder consumeGases = new();
        if (msg.ConsumeGases != null)
        {
            foreach (var gas in msg.ConsumeGases)
            {
                consumeGases.Append(IndentedNewline);
                consumeGases.Append(gas);
            }
        }

        if (msg.IsTray)
            PlantName.Text = Loc.GetString("plant-analyzer-window-label-name-scanned-plant", ("seedName", Loc.GetString(string.IsNullOrEmpty(msg.SeedName) ? "plant-analyzer-unknown-plant" : msg.SeedName)));
        else
            PlantName.Text = Loc.GetString("plant-analyzer-window-label-name-scanned-seed", ("seedName", Loc.GetString(string.IsNullOrEmpty(msg.SeedName) ? "plant-analyzer-unknown-plant" : msg.SeedName)));
        // Basics
        PlantYield.Text = Loc.GetString("plant-analyzer-plant-yield-text", ("seedYield", $"{msg.SeedYield:D0}"));
        Potency.Text = Loc.GetString("plant-analyzer-plant-potency-text", ("seedPotency", $"{msg.SeedPotency:F0}"));
        Repeat.Text = Loc.GetString("plant-analyzer-plant-harvest-text", ("plantHarvestType", Loc.GetString($"plant-analyzer-harvest-{msg.HarvestType}").ToString()));
        Endurance.Text = Loc.GetString("plant-analyzer-plant-endurance-text", ("seedEndurance", $"{msg.Endurance:F0}"));
        Chemicals.Text = Loc.GetString("plant-analyzer-plant-chemistry-text", ("seedChem", chemString));
        ExudeGases.Text = Loc.GetString("plant-analyzer-plant-exude-text", ("gases", exudeGases.Length == 0 ? Loc.GetString("plant-analyzer-plant-gases-none") : exudeGases.ToString()));
        ConsumeGases.Text = Loc.GetString("plant-analyzer-plant-consume-text", ("gases", consumeGases.Length == 0 ? Loc.GetString("plant-analyzer-plant-gases-none") : consumeGases.ToString()));
        Lifespan.Text = Loc.GetString("plant-analyzer-plant-lifespan-text", ("lifespan", $"{msg.Lifespan:F1}"));
        Maturation.Text = Loc.GetString("plant-analyzer-plant-maturation-text", ("maturation", $"{msg.Maturation:F1}"));
        Production.Text = Loc.GetString("plant-analyzer-plant-production-text", ("production", $"{msg.Production:F1}"));
        GrowthStages.Text = Loc.GetString("plant-analyzer-plant-growthstages-text", ("growthStages", $"{msg.GrowthStages:D0}"));
        // Tolerances
        NutrientUsage.Text = Loc.GetString("plant-analyzer-tolerance-nutrient-usage", ("nutrientUsage", $"{msg.NutrientConsumption:F2}"));
        WaterUsage.Text = Loc.GetString("plant-analyzer-tolerance-water-usage", ("waterUsage", $"{msg.WaterConsumption:F2}"));
        IdealHeat.Text = Loc.GetString("plant-analyzer-tolerance-ideal-heat", ("idealHeat", $"{msg.IdealHeat:F0}"));
        HeatTolerance.Text = Loc.GetString("plant-analyzer-tolerance-heat-tolerance", ("heatTolerance", $"{msg.HeatTolerance:F1}"));
        IdealLight.Text = Loc.GetString("plant-analyzer-tolerance-ideal-light", ("idealLight", $"{msg.IdealLight:F1}"));
        LightTolerance.Text = Loc.GetString("plant-analyzer-tolerance-light-tolerance", ("lightTolerance", $"{msg.LightTolerance:F1}"));
        ToxinsTolerance.Text = Loc.GetString("plant-analyzer-tolerance-toxin-tolerance", ("toxinsTolerance", $"{msg.ToxinsTolerance:F1}"));
        LowPressureTolerance.Text = Loc.GetString("plant-analyzer-tolerance-low-pressure", ("lowPressureTolerance", $"{msg.LowPressureTolerance:F1}")); ;
        HighPressureTolerance.Text = Loc.GetString("plant-analyzer-tolerance-high-pressure", ("highPressureTolerance", $"{msg.HighPressureTolerance:F1}"));
        PestTolerance.Text = Loc.GetString("plant-analyzer-tolerance-pest-tolerance", ("pestTolerance", $"{msg.PestTolerance:F1}"));
        WeedTolerance.Text = Loc.GetString("plant-analyzer-tolerance-weed-tolerance", ("weedTolerance", $"{msg.WeedTolerance:F1}"));
        // Misc
        StringBuilder mutations = new();
        if (msg.Mutations.HasFlag(MutationFlags.TurnIntoKudzu))
        {
            mutations.Append(IndentedNewline);
            mutations.Append(Loc.GetString("plant-analyzer-mutation-turnintokudzu"));
        }
        if (msg.Mutations.HasFlag(MutationFlags.Seedless))
        {
            mutations.Append(IndentedNewline);
            mutations.Append(Loc.GetString("plant-analyzer-mutation-seedless"));
        }
        if (msg.Mutations.HasFlag(MutationFlags.Slip))
        {
            mutations.Append(IndentedNewline);
            mutations.Append(Loc.GetString("plant-analyzer-mutation-slip"));
        }
        if (msg.Mutations.HasFlag(MutationFlags.Sentient))
        {
            mutations.Append(IndentedNewline);
            mutations.Append(Loc.GetString("plant-analyzer-mutation-sentient"));
        }
        if (msg.Mutations.HasFlag(MutationFlags.Ligneous))
        {
            mutations.Append(IndentedNewline);
            mutations.Append(Loc.GetString("plant-analyzer-mutation-ligneous"));
        }
        if (msg.Mutations.HasFlag(MutationFlags.CanScream))
        {
            mutations.Append(IndentedNewline);
            mutations.Append(Loc.GetString("plant-analyzer-mutation-canscream"));
        }

        Traits.Text = Loc.GetString("plant-analyzer-plant-mutations-text", ("traits", mutations.ToString()));
        
        StringBuilder speciation = new();
        if (msg.Speciation is null)
        {
            speciation.Append("-");
        }
        else
        {
            foreach (var species in msg.Speciation)
            {
                speciation.Append(IndentedNewline);
                speciation.Append(Loc.GetString(species));
            }
        }

        PlantSpeciation.Text = Loc.GetString("plant-analyzer-plant-speciation-text", ("speciation", speciation.ToString()));
    }

}
